import '@nx-starter/shared/styles/global.scss';
import { NextAuthProvider } from '../providers/NextAuthProvider';
import { Noto_Sans, Work_Sans } from 'next/font/google'
export const metadata = {
  title: 'Welcome to web-app',
  description: 'Generated by create-nx-workspace',
};

const noto_sans = Noto_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-noto-sans',
  weight: ["400", "600", "700"]
});
const work_sans = Work_Sans({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-work-sans',
  weight: ['400', '600', "700"],
});


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${noto_sans.variable} ${work_sans.variable}`}>
      <body>
        <NextAuthProvider>
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
