import '@nx-starter/shared/styles/global.scss';
import { NextAuthProvider } from '../providers/NextAuthProvider';
export const metadata = {
  title: 'Welcome to web-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          {children}
        </NextAuthProvider>
      </body>
    </html>
  );
}
